import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

def clean_dataset(df):
    """
    Crucial Constraint: Remove Infinity and NaN values generated by CICFlowMeter.
    """
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    return df[indices_to_keep].reset_index(drop=True)

def main():
    print("Loading dataset...")
    # For demonstration, we will create a dummy subset if no CSV is found.
    # Replace 'cic_ids_subset.csv' with your actual dataset file.
    try:
        df = pd.read_csv('cic_ids_subset.csv')
    except FileNotFoundError:
        print("Dataset 'cic_ids_subset.csv' not found. Generating dummy data for pipeline validation...")
        np.random.seed(42)
        dummy_data = {
            'Flow Duration': np.random.rand(1000) * 1000,
            'Flow IAT Mean': np.random.rand(1000) * 100,
            'Total Fwd Packets': np.random.randint(1, 100, 1000),
            'Total Backward Packets': np.random.randint(1, 100, 1000),
            'Fwd Packet Length Max': np.random.randint(1, 1500, 1000),
            'Label': np.random.choice(['BENIGN', 'DDoS', 'PortScan'], 1000)
        }
        df = pd.DataFrame(dummy_data)
        # Inject some NaNs and Infs to test the cleaning logic
        df.loc[10:15, 'Flow Duration'] = np.inf
        df.loc[20:25, 'Total Fwd Packets'] = np.nan

    print(f"Original dataset shape: {df.shape}")
    
    # 1. Clean data (Crucial Constraint)
    print("Cleaning Infinity and NaN values...")
    df = clean_dataset(df)
    print(f"Cleaned dataset shape: {df.shape}")

    # Separate features and target
    X = df.drop('Label', axis=1)
    y = df['Label']

    # 2. Baseline Model
    print("\n--- Training Baseline Model ---")
    X_train_base, X_test_base, y_train_base, y_test_base = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler_base = StandardScaler()
    X_train_base_scaled = scaler_base.fit_transform(X_train_base)
    X_test_base_scaled = scaler_base.transform(X_test_base)

    baseline_clf = RandomForestClassifier(n_estimators=100, random_state=42)
    baseline_clf.fit(X_train_base_scaled, y_train_base)
    base_preds = baseline_clf.predict(X_test_base_scaled)
    base_acc = accuracy_score(y_test_base, base_preds)
    print(f"Baseline Accuracy: {base_acc:.4f}")

    # 3. Ablated Model (Removing 'Flow Duration' and 'IAT' features)
    print("\n--- Training Ablated Model ---")
    time_features = [col for col in X.columns if 'Duration' in col or 'IAT' in col]
    print(f"Removing time-based features: {time_features}")
    
    X_ablated = X.drop(columns=time_features)
    X_train_abl, X_test_abl, y_train_abl, y_test_abl = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    scaler_abl = StandardScaler()
    X_train_abl_scaled = scaler_abl.fit_transform(X_train_abl)
    X_test_abl_scaled = scaler_abl.transform(X_test_abl)

    ablated_clf = RandomForestClassifier(n_estimators=100, random_state=42)
    ablated_clf.fit(X_train_abl_scaled, y_train_abl)
    abl_preds = ablated_clf.predict(X_test_abl_scaled)
    abl_acc = accuracy_score(y_test_abl, abl_preds)
    print(f"Ablated Accuracy: {abl_acc:.4f}")

    # 4. Export the Best Performing Model & Scaler
    if base_acc >= abl_acc:
        print("\nExporting Baseline Model (Best Performer)...")
        best_model = baseline_clf
        best_scaler = scaler_base
        best_features = list(X.columns)
    else:
        print("\nExporting Ablated Model (Best Performer)...")
        best_model = ablated_clf
        best_scaler = scaler_abl
        best_features = list(X_ablated.columns)

    # Save feature names so the API knows the exact expected column order
    joblib.dump(best_model, 'model.pkl')
    joblib.dump(best_scaler, 'scaler.pkl')
    joblib.dump(best_features, 'model_features.pkl')
    print("Exported 'model.pkl', 'scaler.pkl', and 'model_features.pkl' successfully.")

if __name__ == "__main__":
    main()
