import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

def clean_dataset(df):
    """
    Crucial Constraint: Remove Infinity and NaN values generated by CICFlowMeter.
    """
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    return df[indices_to_keep].reset_index(drop=True)

def main():
    print("Loading dataset...")
    import glob
    import os
    
    dataset_dir = 'Dataset'
    if not os.path.exists(dataset_dir):
        raise FileNotFoundError(f"Dataset directory '{dataset_dir}' not found. Please run the aws s3 sync command first.")
        
    # Specifically target the processed CSV files
    csv_files = glob.glob(f'{dataset_dir}/**/*.csv', recursive=True)
    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in '{dataset_dir}'.")
        
    print(f"Found {len(csv_files)} CSV files. Loading data...")
    
    # We will sample from each file to build a representative subset without running out of memory
    dfs = []
    for f in csv_files:
        print(f"Sampling from {os.path.basename(f)}...")
        try:
            # CIC-IDS-2018 CSVs can be huge, we read a sample (e.g., 100k rows)
            df_part = pd.read_csv(f, nrows=100000) 
            dfs.append(df_part)
        except Exception as e:
            print(f"Could not read {f}: {e}")
            
    if not dfs:
        raise ValueError("Could not load any data from the CSV files.")
        
    df = pd.concat(dfs, ignore_index=True)
    
    # Standardize column names (CIC-IDS datasets often have leading/trailing spaces)
    df.columns = df.columns.str.strip()

    print(f"Original dataset shape: {df.shape}")
    
    # 1. Clean data (Crucial Constraint)
    print("Cleaning Infinity and NaN values...")
    df = clean_dataset(df)
    print(f"Cleaned dataset shape: {df.shape}")

    # Separate features and target
    X = df.drop('Label', axis=1)
    y = df['Label']

    # 2. Baseline Model
    print("\n--- Training Baseline Model ---")
    X_train_base, X_test_base, y_train_base, y_test_base = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler_base = StandardScaler()
    X_train_base_scaled = scaler_base.fit_transform(X_train_base)
    X_test_base_scaled = scaler_base.transform(X_test_base)

    baseline_clf = RandomForestClassifier(n_estimators=100, random_state=42)
    baseline_clf.fit(X_train_base_scaled, y_train_base)
    base_preds = baseline_clf.predict(X_test_base_scaled)
    base_acc = accuracy_score(y_test_base, base_preds)
    print(f"Baseline Accuracy: {base_acc:.4f}")

    # 3. Ablated Model (Removing 'Flow Duration' and 'IAT' features)
    print("\n--- Training Ablated Model ---")
    time_features = [col for col in X.columns if 'Duration' in col or 'IAT' in col]
    print(f"Removing time-based features: {time_features}")
    
    X_ablated = X.drop(columns=time_features)
    X_train_abl, X_test_abl, y_train_abl, y_test_abl = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    scaler_abl = StandardScaler()
    X_train_abl_scaled = scaler_abl.fit_transform(X_train_abl)
    X_test_abl_scaled = scaler_abl.transform(X_test_abl)

    ablated_clf = RandomForestClassifier(n_estimators=100, random_state=42)
    ablated_clf.fit(X_train_abl_scaled, y_train_abl)
    abl_preds = ablated_clf.predict(X_test_abl_scaled)
    abl_acc = accuracy_score(y_test_abl, abl_preds)
    print(f"Ablated Accuracy: {abl_acc:.4f}")

    # 4. Export the Best Performing Model & Scaler
    if base_acc >= abl_acc:
        print("\nExporting Baseline Model (Best Performer)...")
        best_model = baseline_clf
        best_scaler = scaler_base
        best_features = list(X.columns)
    else:
        print("\nExporting Ablated Model (Best Performer)...")
        best_model = ablated_clf
        best_scaler = scaler_abl
        best_features = list(X_ablated.columns)

    # Save feature names so the API knows the exact expected column order
    joblib.dump(best_model, 'model.pkl')
    joblib.dump(best_scaler, 'scaler.pkl')
    joblib.dump(best_features, 'model_features.pkl')
    print("Exported 'model.pkl', 'scaler.pkl', and 'model_features.pkl' successfully.")

if __name__ == "__main__":
    main()
